APPS = {
    "Browsers": [
        {
            "id": "firefox",
            "name": "Firefox",
            "description": "Fast, privacy-focused web browser.",
            "icon": "firefox",
            "packages": {"apt": "firefox", "pacman": "firefox", "dnf": "firefox", "zypper": "MozillaFirefox"},
            "flatpak": "org.mozilla.firefox",
        },
        {
            "id": "chromium",
            "name": "Chromium",
            "description": "Open-source Chromium browser.",
            "icon": "chromium",
            "packages": {"apt": "chromium-browser", "pacman": "chromium", "dnf": "chromium", "zypper": "chromium"},
            "flatpak": "org.chromium.Chromium",
        },
        {
            "id": "brave",
            "name": "Brave",
            "description": "Privacy-focused browser. Native package may require extra repository.",
            "icon": "web-browser",
            "packages": {"apt": "brave-browser", "pacman": "brave", "dnf": "brave-browser", "zypper": "brave-browser"},
            "flatpak": "com.brave.Browser",
        },
        {
            "id": "vivaldi",
            "name": "Vivaldi",
            "description": "Feature-rich browser for power users.",
            "icon": "web-browser",
            "packages": {"apt": "vivaldi-stable", "pacman": "vivaldi", "dnf": "vivaldi-stable", "zypper": "vivaldi-stable"},
            "flatpak": "com.vivaldi.Vivaldi",
        },
    ],
    "Development": [
        {
            "id": "git",
            "name": "Git",
            "description": "Distributed version control system.",
            "icon": "git",
            "packages": {"apt": "git", "pacman": "git", "dnf": "git", "zypper": "git"},
        },
        {
            "id": "vscode",
            "name": "Visual Studio Code",
            "description": "Code editor. Native package may require third-party repository on some distros.",
            "icon": "code",
            "packages": {"apt": "code", "pacman": "code", "dnf": "code", "zypper": "code"},
            "flatpak": "com.visualstudio.code",
        },
        {
            "id": "vscodium",
            "name": "VSCodium",
            "description": "Telemetry-free build of VS Code.",
            "icon": "code",
            "packages": {"apt": "codium", "pacman": "codium", "dnf": "codium", "zypper": "codium"},
            "flatpak": "com.vscodium.codium",
        },
        {
            "id": "docker",
            "name": "Docker",
            "description": "Container runtime and tooling.",
            "icon": "docker",
            "packages": {"apt": "docker.io", "pacman": "docker", "dnf": "docker", "zypper": "docker"},
        },
        {
            "id": "nodejs",
            "name": "Node.js",
            "description": "JavaScript runtime.",
            "icon": "applications-development",
            "packages": {"apt": "nodejs", "pacman": "nodejs", "dnf": "nodejs", "zypper": "nodejs"},
        },
        {
            "id": "python3",
            "name": "Python 3",
            "description": "Python programming language.",
            "icon": "applications-development",
            "packages": {"apt": "python3", "pacman": "python", "dnf": "python3", "zypper": "python3"},
        },
        {
            "id": "postman",
            "name": "Postman",
            "description": "API testing and development platform.",
            "icon": "applications-internet",
            "packages": {"apt": "postman", "pacman": "postman-bin", "dnf": "postman", "zypper": "postman"},
            "flatpak": "com.getpostman.Postman",
        },
    ],
    "Multimedia": [
        {
            "id": "vlc",
            "name": "VLC",
            "description": "Universal media player.",
            "icon": "vlc",
            "packages": {"apt": "vlc", "pacman": "vlc", "dnf": "vlc", "zypper": "vlc"},
            "flatpak": "org.videolan.VLC",
        },
        {
            "id": "gimp",
            "name": "GIMP",
            "description": "Image editor.",
            "icon": "gimp",
            "packages": {"apt": "gimp", "pacman": "gimp", "dnf": "gimp", "zypper": "gimp"},
            "flatpak": "org.gimp.GIMP",
        },
        {
            "id": "obs-studio",
            "name": "OBS Studio",
            "description": "Streaming and screen recording software.",
            "icon": "camera-video",
            "packages": {"apt": "obs-studio", "pacman": "obs-studio", "dnf": "obs-studio", "zypper": "obs-studio"},
            "flatpak": "com.obsproject.Studio",
        },
        {
            "id": "kdenlive",
            "name": "Kdenlive",
            "description": "Video editor.",
            "icon": "applications-multimedia",
            "packages": {"apt": "kdenlive", "pacman": "kdenlive", "dnf": "kdenlive", "zypper": "kdenlive"},
            "flatpak": "org.kde.kdenlive",
        },
        {
            "id": "audacity",
            "name": "Audacity",
            "description": "Audio editor and recorder.",
            "icon": "audio-x-generic",
            "packages": {"apt": "audacity", "pacman": "audacity", "dnf": "audacity", "zypper": "audacity"},
            "flatpak": "org.audacityteam.Audacity",
        },
        {
            "id": "spotify",
            "name": "Spotify",
            "description": "Music streaming application.",
            "icon": "multimedia-player",
            "packages": {"apt": "spotify-client", "pacman": "spotify-launcher", "dnf": "spotify-client", "zypper": "spotify-client"},
            "flatpak": "com.spotify.Client",
        },
    ],
    "Communication": [
        {
            "id": "telegram",
            "name": "Telegram Desktop",
            "description": "Desktop client for Telegram.",
            "icon": "telegram",
            "packages": {"apt": "telegram-desktop", "pacman": "telegram-desktop", "dnf": "telegram-desktop", "zypper": "telegram-desktop"},
            "flatpak": "org.telegram.desktop",
        },
        {
            "id": "discord",
            "name": "Discord",
            "description": "Voice, chat and community platform.",
            "icon": "discord",
            "packages": {"apt": "discord", "pacman": "discord", "dnf": "discord", "zypper": "discord"},
            "flatpak": "com.discordapp.Discord",
        },
        {
            "id": "thunderbird",
            "name": "Thunderbird",
            "description": "Email client.",
            "icon": "thunderbird",
            "packages": {"apt": "thunderbird", "pacman": "thunderbird", "dnf": "thunderbird", "zypper": "MozillaThunderbird"},
            "flatpak": "org.mozilla.Thunderbird",
        },
        {
            "id": "signal",
            "name": "Signal",
            "description": "Secure messaging application.",
            "icon": "mail-message-new",
            "packages": {"apt": "signal-desktop", "pacman": "signal-desktop", "dnf": "signal-desktop", "zypper": "signal-desktop"},
            "flatpak": "org.signal.Signal",
        },
    ],
    "Utilities": [
        {
            "id": "htop",
            "name": "htop",
            "description": "Interactive process viewer.",
            "icon": "utilities-system-monitor",
            "packages": {"apt": "htop", "pacman": "htop", "dnf": "htop", "zypper": "htop"},
        },
        {
            "id": "timeshift",
            "name": "Timeshift",
            "description": "System snapshot utility.",
            "icon": "document-save",
            "packages": {"apt": "timeshift", "pacman": "timeshift", "dnf": "timeshift", "zypper": "timeshift"},
        },
        {
            "id": "filezilla",
            "name": "FileZilla",
            "description": "FTP/SFTP client.",
            "icon": "folder-remote",
            "packages": {"apt": "filezilla", "pacman": "filezilla", "dnf": "filezilla", "zypper": "filezilla"},
            "flatpak": "org.filezillaproject.Filezilla",
        },
        {
            "id": "qbittorrent",
            "name": "qBittorrent",
            "description": "BitTorrent client.",
            "icon": "folder-download",
            "packages": {"apt": "qbittorrent", "pacman": "qbittorrent", "dnf": "qbittorrent", "zypper": "qbittorrent"},
            "flatpak": "org.qbittorrent.qBittorrent",
        },
        {
            "id": "flatseal",
            "name": "Flatseal",
            "description": "Manage Flatpak permissions.",
            "icon": "preferences-system",
            "packages": {"apt": "", "pacman": "", "dnf": "", "zypper": ""},
            "flatpak": "com.github.tchx84.Flatseal",
        },
        {
            "id": "bleachbit",
            "name": "BleachBit",
            "description": "Privacy and cleanup utility.",
            "icon": "edit-clear",
            "packages": {"apt": "bleachbit", "pacman": "bleachbit", "dnf": "bleachbit", "zypper": "bleachbit"},
            "flatpak": "org.bleachbit.BleachBit",
        },
    ],
}
