APPS = {
    "Browsers": [
        {
            "id": "firefox",
            "name": "Firefox",
            "description": "Fast, privacy-focused web browser.",
            "icon": "firefox",
            "packages": {"apt": "firefox", "pacman": "firefox", "dnf": "firefox", "zypper": "MozillaFirefox"},
            "flatpak": "org.mozilla.firefox",
        },
        {
            "id": "chromium",
            "name": "Chromium",
            "description": "Open-source Chromium browser.",
            "icon": "chromium",
            "packages": {"apt": "chromium-browser", "pacman": "chromium", "dnf": "chromium", "zypper": "chromium"},
            "flatpak": "org.chromium.Chromium",
        },
        {
            "id": "brave",
            "name": "Brave",
            "description": "Privacy-focused browser. Native package may require extra repository.",
            "icon": "web-browser",
            "packages": {"apt": "brave-browser", "pacman": "brave", "dnf": "brave-browser", "zypper": "brave-browser"},
            "flatpak": "com.brave.Browser",
        },
        {
            "id": "vivaldi",
            "name": "Vivaldi",
            "description": "Feature-rich browser for power users.",
            "icon": "web-browser",
            "packages": {"apt": "vivaldi-stable", "pacman": "vivaldi", "dnf": "vivaldi-stable", "zypper": "vivaldi-stable"},
            "flatpak": "com.vivaldi.Vivaldi",
        },
        {
            "id": "opera",
            "name": "Opera",
            "description": "Feature-rich browser with built-in VPN.",
            "icon": "web-browser",
            "packages": {"apt": "opera-stable", "pacman": "opera", "dnf": "opera-stable", "zypper": "opera"},
            "flatpak": "com.opera.Opera",
        },
        {
            "id": "tor",
            "name": "Tor Browser",
            "description": "Privacy-focused browser using Tor network.",
            "icon": "web-browser",
            "packages": {"apt": "torbrowser-launcher", "pacman": "torbrowser-launcher", "dnf": "torbrowser-launcher", "zypper": "torbrowser-launcher"},
            "flatpak": "com.github.micahflee.torbrowser-launcher",
        },
    ],
    "Development": [
        {
            "id": "git",
            "name": "Git",
            "description": "Distributed version control system.",
            "icon": "git",
            "packages": {"apt": "git", "pacman": "git", "dnf": "git", "zypper": "git"},
        },
        {
            "id": "vscode",
            "name": "Visual Studio Code",
            "description": "Code editor. Native package may require third-party repository on some distros.",
            "icon": "code",
            "packages": {"apt": "code", "pacman": "code", "dnf": "code", "zypper": "code"},
            "flatpak": "com.visualstudio.code",
        },
        {
            "id": "vscodium",
            "name": "VSCodium",
            "description": "Telemetry-free build of VS Code.",
            "icon": "code",
            "packages": {"apt": "codium", "pacman": "codium", "dnf": "codium", "zypper": "codium"},
            "flatpak": "com.vscodium.codium",
        },
        {
            "id": "docker",
            "name": "Docker",
            "description": "Container runtime and tooling.",
            "icon": "docker",
            "packages": {"apt": "docker.io", "pacman": "docker", "dnf": "docker", "zypper": "docker"},
        },
        {
            "id": "nodejs",
            "name": "Node.js",
            "description": "JavaScript runtime.",
            "icon": "applications-development",
            "packages": {"apt": "nodejs", "pacman": "nodejs", "dnf": "nodejs", "zypper": "nodejs"},
        },
        {
            "id": "python3",
            "name": "Python 3",
            "description": "Python programming language.",
            "icon": "applications-development",
            "packages": {"apt": "python3", "pacman": "python", "dnf": "python3", "zypper": "python3"},
        },
        {
            "id": "postman",
            "name": "Postman",
            "description": "API testing and development platform.",
            "icon": "applications-internet",
            "packages": {"apt": "postman", "pacman": "postman-bin", "dnf": "postman", "zypper": "postman"},
            "flatpak": "com.getpostman.Postman",
        },
        {
            "id": "intellij",
            "name": "IntelliJ IDEA Community",
            "description": "Java IDE by JetBrains.",
            "icon": "code",
            "packages": {"apt": "intellij-idea-community", "pacman": "intellij-idea-community-edition", "dnf": "intellij-idea-community", "zypper": "intellij-idea-community"},
            "flatpak": "com.jetbrains.IntelliJ-IDEA-Community",
        },
        {
            "id": "pycharm",
            "name": "PyCharm Community",
            "description": "Python IDE by JetBrains.",
            "icon": "code",
            "packages": {"apt": "pycharm-community", "pacman": "pycharm-community-edition", "dnf": "pycharm-community", "zypper": "pycharm-community"},
            "flatpak": "com.jetbrains.PyCharm-Community",
        },
        {
            "id": "android-studio",
            "name": "Android Studio",
            "description": "IDE for Android development.",
            "icon": "applications-development",
            "packages": {"apt": "android-studio", "pacman": "android-studio", "dnf": "android-studio", "zypper": "android-studio"},
            "flatpak": "com.google.AndroidStudio",
        },
        {
            "id": "dbeaver",
            "name": "DBeaver",
            "description": "Universal database tool.",
            "icon": "database",
            "packages": {"apt": "dbeaver-ce", "pacman": "dbeaver", "dnf": "dbeaver", "zypper": "dbeaver"},
            "flatpak": "io.dbeaver.DBeaverCommunity",
        },
        {
            "id": "insomnia",
            "name": "Insomnia",
            "description": "API client alternative to Postman.",
            "icon": "applications-internet",
            "packages": {"apt": "insomnia", "pacman": "insomnia", "dnf": "insomnia", "zypper": "insomnia"},
            "flatpak": "rest.insomnia.Insomnia",
        },
    ],
    "Multimedia": [
        {
            "id": "vlc",
            "name": "VLC",
            "description": "Universal media player.",
            "icon": "vlc",
            "packages": {"apt": "vlc", "pacman": "vlc", "dnf": "vlc", "zypper": "vlc"},
            "flatpak": "org.videolan.VLC",
        },
        {
            "id": "gimp",
            "name": "GIMP",
            "description": "Image editor.",
            "icon": "gimp",
            "packages": {"apt": "gimp", "pacman": "gimp", "dnf": "gimp", "zypper": "gimp"},
            "flatpak": "org.gimp.GIMP",
        },
        {
            "id": "obs-studio",
            "name": "OBS Studio",
            "description": "Streaming and screen recording software.",
            "icon": "camera-video",
            "packages": {"apt": "obs-studio", "pacman": "obs-studio", "dnf": "obs-studio", "zypper": "obs-studio"},
            "flatpak": "com.obsproject.Studio",
        },
        {
            "id": "kdenlive",
            "name": "Kdenlive",
            "description": "Video editor.",
            "icon": "applications-multimedia",
            "packages": {"apt": "kdenlive", "pacman": "kdenlive", "dnf": "kdenlive", "zypper": "kdenlive"},
            "flatpak": "org.kde.kdenlive",
        },
        {
            "id": "audacity",
            "name": "Audacity",
            "description": "Audio editor and recorder.",
            "icon": "audio-x-generic",
            "packages": {"apt": "audacity", "pacman": "audacity", "dnf": "audacity", "zypper": "audacity"},
            "flatpak": "org.audacityteam.Audacity",
        },
        {
            "id": "spotify",
            "name": "Spotify",
            "description": "Music streaming application.",
            "icon": "multimedia-player",
            "packages": {"apt": "spotify-client", "pacman": "spotify-launcher", "dnf": "spotify-client", "zypper": "spotify-client"},
            "flatpak": "com.spotify.Client",
        },
        {
            "id": "handbrake",
            "name": "HandBrake",
            "description": "Video transcoder.",
            "icon": "applications-multimedia",
            "packages": {"apt": "handbrake", "pacman": "handbrake", "dnf": "handbrake", "zypper": "handbrake"},
            "flatpak": "fr.handbrake.ghb",
        },
        {
            "id": "krita",
            "name": "Krita",
            "description": "Digital painting software.",
            "icon": "applications-graphics",
            "packages": {"apt": "krita", "pacman": "krita", "dnf": "krita", "zypper": "krita"},
            "flatpak": "org.kde.krita",
        },
        {
            "id": "inkscape",
            "name": "Inkscape",
            "description": "Vector graphics editor.",
            "icon": "applications-graphics",
            "packages": {"apt": "inkscape", "pacman": "inkscape", "dnf": "inkscape", "zypper": "inkscape"},
            "flatpak": "org.inkscape.Inkscape",
        },
        {
            "id": "blender",
            "name": "Blender",
            "description": "3D creation suite.",
            "icon": "applications-graphics",
            "packages": {"apt": "blender", "pacman": "blender", "dnf": "blender", "zypper": "blender"},
            "flatpak": "org.blender.Blender",
        },
    ],
    "Communication": [
        {
            "id": "telegram",
            "name": "Telegram Desktop",
            "description": "Desktop client for Telegram.",
            "icon": "telegram",
            "packages": {"apt": "telegram-desktop", "pacman": "telegram-desktop", "dnf": "telegram-desktop", "zypper": "telegram-desktop"},
            "flatpak": "org.telegram.desktop",
        },
        {
            "id": "discord",
            "name": "Discord",
            "description": "Voice, chat and community platform.",
            "icon": "discord",
            "packages": {"apt": "discord", "pacman": "discord", "dnf": "discord", "zypper": "discord"},
            "flatpak": "com.discordapp.Discord",
        },
        {
            "id": "thunderbird",
            "name": "Thunderbird",
            "description": "Email client.",
            "icon": "thunderbird",
            "packages": {"apt": "thunderbird", "pacman": "thunderbird", "dnf": "thunderbird", "zypper": "MozillaThunderbird"},
            "flatpak": "org.mozilla.Thunderbird",
        },
        {
            "id": "signal",
            "name": "Signal",
            "description": "Secure messaging application.",
            "icon": "mail-message-new",
            "packages": {"apt": "signal-desktop", "pacman": "signal-desktop", "dnf": "signal-desktop", "zypper": "signal-desktop"},
            "flatpak": "org.signal.Signal",
        },
        {
            "id": "slack",
            "name": "Slack",
            "description": "Team communication platform.",
            "icon": "internet-chat",
            "packages": {"apt": "slack-desktop", "pacman": "slack-desktop", "dnf": "slack", "zypper": "slack"},
            "flatpak": "com.slack.Slack",
        },
        {
            "id": "zoom",
            "name": "Zoom",
            "description": "Video conferencing tool.",
            "icon": "camera-web",
            "packages": {"apt": "zoom", "pacman": "zoom", "dnf": "zoom", "zypper": "zoom"},
            "flatpak": "us.zoom.Zoom",
        },
        {
            "id": "element",
            "name": "Element",
            "description": "Matrix-based secure chat.",
            "icon": "internet-chat",
            "packages": {"apt": "element-desktop", "pacman": "element-desktop", "dnf": "element", "zypper": "element-desktop"},
            "flatpak": "im.riot.Riot",
        },
    ],
    "Utilities": [
        {
            "id": "htop",
            "name": "htop",
            "description": "Interactive process viewer.",
            "icon": "utilities-system-monitor",
            "packages": {"apt": "htop", "pacman": "htop", "dnf": "htop", "zypper": "htop"},
        },
        {
            "id": "timeshift",
            "name": "Timeshift",
            "description": "System snapshot utility.",
            "icon": "document-save",
            "packages": {"apt": "timeshift", "pacman": "timeshift", "dnf": "timeshift", "zypper": "timeshift"},
        },
        {
            "id": "filezilla",
            "name": "FileZilla",
            "description": "FTP/SFTP client.",
            "icon": "folder-remote",
            "packages": {"apt": "filezilla", "pacman": "filezilla", "dnf": "filezilla", "zypper": "filezilla"},
            "flatpak": "org.filezillaproject.Filezilla",
        },
        {
            "id": "qbittorrent",
            "name": "qBittorrent",
            "description": "BitTorrent client.",
            "icon": "folder-download",
            "packages": {"apt": "qbittorrent", "pacman": "qbittorrent", "dnf": "qbittorrent", "zypper": "qbittorrent"},
            "flatpak": "org.qbittorrent.qBittorrent",
        },
        {
            "id": "flatseal",
            "name": "Flatseal",
            "description": "Manage Flatpak permissions.",
            "icon": "preferences-system",
            "packages": {"apt": "", "pacman": "", "dnf": "", "zypper": ""},
            "flatpak": "com.github.tchx84.Flatseal",
        },
        {
            "id": "bleachbit",
            "name": "BleachBit",
            "description": "Privacy and cleanup utility.",
            "icon": "edit-clear",
            "packages": {"apt": "bleachbit", "pacman": "bleachbit", "dnf": "bleachbit", "zypper": "bleachbit"},
            "flatpak": "org.bleachbit.BleachBit",
        },
        {
            "id": "neofetch",
            "name": "Neofetch",
            "description": "System information tool.",
            "icon": "utilities-terminal",
            "packages": {"apt": "neofetch", "pacman": "neofetch", "dnf": "neofetch", "zypper": "neofetch"},
        },
        {
            "id": "stacer",
            "name": "Stacer",
            "description": "System optimizer and monitor.",
            "icon": "utilities-system-monitor",
            "packages": {"apt": "stacer", "pacman": "stacer", "dnf": "stacer", "zypper": "stacer"},
            "flatpak": "com.github.oguzhaninan.Stacer",
        },
        {
            "id": "gnome-disk-utility",
            "name": "Disks",
            "description": "Disk management tool.",
            "icon": "drive-harddisk",
            "packages": {"apt": "gnome-disk-utility", "pacman": "gnome-disk-utility", "dnf": "gnome-disk-utility", "zypper": "gnome-disk-utility"},
        },
        {
            "id": "gparted",
            "name": "GParted",
            "description": "Partition editor.",
            "icon": "drive-harddisk",
            "packages": {"apt": "gparted", "pacman": "gparted", "dnf": "gparted", "zypper": "gparted"},
            "flatpak": "org.gnome.GParted",
        },
    ],
    "Office": [
        {
            "id": "libreoffice",
            "name": "LibreOffice",
            "description": "Office suite.",
            "icon": "x-office-document",
            "packages": {"apt": "libreoffice", "pacman": "libreoffice-fresh", "dnf": "libreoffice", "zypper": "libreoffice"},
            "flatpak": "org.libreoffice.LibreOffice",
        },
        {
            "id": "onlyoffice",
            "name": "ONLYOFFICE",
            "description": "Office suite alternative.",
            "icon": "x-office-document",
            "packages": {"apt": "onlyoffice-desktopeditors", "pacman": "onlyoffice-bin", "dnf": "onlyoffice-desktopeditors", "zypper": "onlyoffice"},
            "flatpak": "org.onlyoffice.desktopeditors",
        },
    ],
    "Gaming": [
        {
            "id": "steam",
            "name": "Steam",
            "description": "Gaming platform by Valve.",
            "icon": "steam",
            "packages": {"apt": "steam", "pacman": "steam", "dnf": "steam", "zypper": "steam"},
            "flatpak": "com.valvesoftware.Steam",
        },
        {
            "id": "lutris",
            "name": "Lutris",
            "description": "Game manager for Linux.",
            "icon": "applications-games",
            "packages": {"apt": "lutris", "pacman": "lutris", "dnf": "lutris", "zypper": "lutris"},
            "flatpak": "net.lutris.Lutris",
        },
    ],
}
