#!/usr/bin/env python3
"""
TuxPulse - Applications Catalog
Catalog complet + logică avansată de stare (instalat / nativ / flatpak / update)
"""

from __future__ import annotations

import subprocess
import shutil
from copy import deepcopy
from functools import lru_cache
from typing import Dict, List

from core.pkg_backend import PackageBackend

APPS = {'Browsers': [{'id': 'firefox',
               'name': 'Firefox',
               'description': 'Fast, privacy-focused web browser.',
               'icon': 'firefox',
               'packages': {'apt': 'firefox', 'pacman': 'firefox', 'dnf': 'firefox', 'zypper': 'MozillaFirefox'},
               'flatpak': 'org.mozilla.firefox'},
              {'id': 'chromium',
               'name': 'Chromium',
               'description': 'Open-source Chromium browser.',
               'icon': 'chromium',
               'packages': {'apt': 'chromium-browser', 'pacman': 'chromium', 'dnf': 'chromium', 'zypper': 'chromium'},
               'flatpak': 'org.chromium.Chromium'},
              {'id': 'brave',
               'name': 'Brave',
               'description': 'Privacy-focused browser. Native package may require extra repository.',
               'icon': 'web-browser',
               'packages': {'apt': 'brave-browser',
                            'pacman': 'brave',
                            'dnf': 'brave-browser',
                            'zypper': 'brave-browser'},
               'flatpak': 'com.brave.Browser'},
              {'id': 'vivaldi',
               'name': 'Vivaldi',
               'description': 'Feature-rich browser for power users.',
               'icon': 'web-browser',
               'packages': {'apt': 'vivaldi-stable',
                            'pacman': 'vivaldi',
                            'dnf': 'vivaldi-stable',
                            'zypper': 'vivaldi-stable'},
               'flatpak': 'com.vivaldi.Vivaldi'},
              {'id': 'opera',
               'name': 'Opera',
               'description': 'Feature-rich browser with built-in VPN.',
               'icon': 'web-browser',
               'packages': {'apt': 'opera-stable', 'pacman': 'opera', 'dnf': 'opera-stable', 'zypper': 'opera'},
               'flatpak': 'com.opera.Opera'},
              {'id': 'tor',
               'name': 'Tor Browser',
               'description': 'Privacy-focused browser using Tor network.',
               'icon': 'web-browser',
               'packages': {'apt': 'torbrowser-launcher',
                            'pacman': 'torbrowser-launcher',
                            'dnf': 'torbrowser-launcher',
                            'zypper': 'torbrowser-launcher'},
               'flatpak': 'com.github.micahflee.torbrowser-launcher'},
              {'id': 'mullvad-browser',
               'name': 'Mullvad Browser',
               'description': 'Privacy-focused browser. Native packages are officially available for Debian/Ubuntu and '
                              'Fedora; Flatpak is community-maintained.',
               'icon': 'web-browser',
               'packages': {'apt': 'mullvad-browser', 'pacman': '', 'dnf': 'mullvad-browser', 'zypper': ''},
               'flatpak': 'net.mullvad.MullvadBrowser'}],
 'Development': [{'id': 'git',
                  'name': 'Git',
                  'description': 'Distributed version control system.',
                  'icon': 'git',
                  'packages': {'apt': 'git', 'pacman': 'git', 'dnf': 'git', 'zypper': 'git'}},
                 {'id': 'vscode',
                  'name': 'Visual Studio Code',
                  'description': 'Code editor. Native package may require third-party repository on some distros.',
                  'icon': 'code',
                  'packages': {'apt': 'code', 'pacman': 'code', 'dnf': 'code', 'zypper': 'code'},
                  'flatpak': 'com.visualstudio.code'},
                 {'id': 'vscodium',
                  'name': 'VSCodium',
                  'description': 'Telemetry-free build of VS Code.',
                  'icon': 'code',
                  'packages': {'apt': 'codium', 'pacman': 'codium', 'dnf': 'codium', 'zypper': 'codium'},
                  'flatpak': 'com.vscodium.codium'},
                 {'id': 'docker',
                  'name': 'Docker',
                  'description': 'Container runtime and tooling.',
                  'icon': 'docker',
                  'packages': {'apt': 'docker.io', 'pacman': 'docker', 'dnf': 'docker', 'zypper': 'docker'}},
                 {'id': 'nodejs',
                  'name': 'Node.js',
                  'description': 'JavaScript runtime.',
                  'icon': 'applications-development',
                  'packages': {'apt': 'nodejs', 'pacman': 'nodejs', 'dnf': 'nodejs', 'zypper': 'nodejs'}},
                 {'id': 'python3',
                  'name': 'Python 3',
                  'description': 'Python programming language.',
                  'icon': 'applications-development',
                  'packages': {'apt': 'python3', 'pacman': 'python', 'dnf': 'python3', 'zypper': 'python3'}},
                 {'id': 'cmake',
                  'name': 'CMake',
                  'description': 'Cross-platform build system generator.',
                  'icon': 'applications-development',
                  'packages': {'apt': 'cmake', 'pacman': 'cmake', 'dnf': 'cmake', 'zypper': 'cmake'}},
                 {'id': 'jq',
                  'name': 'jq',
                  'description': 'Command-line JSON processor useful for API work and automation.',
                  'icon': 'utilities-terminal',
                  'packages': {'apt': 'jq', 'pacman': 'jq', 'dnf': 'jq', 'zypper': 'jq'}},
                 {'id': 'ripgrep',
                  'name': 'ripgrep',
                  'description': 'Fast recursive search tool for codebases and text files.',
                  'icon': 'utilities-terminal',
                  'packages': {'apt': 'ripgrep', 'pacman': 'ripgrep', 'dnf': 'ripgrep', 'zypper': 'ripgrep'}},
                 {'id': 'tmux',
                  'name': 'tmux',
                  'description': 'Terminal multiplexer for persistent shell sessions.',
                  'icon': 'utilities-terminal',
                  'packages': {'apt': 'tmux', 'pacman': 'tmux', 'dnf': 'tmux', 'zypper': 'tmux'}},
                 {'id': 'postman',
                  'name': 'Postman',
                  'description': 'API testing and development platform.',
                  'icon': 'applications-internet',
                  'packages': {'apt': 'postman', 'pacman': 'postman-bin', 'dnf': 'postman', 'zypper': 'postman'},
                  'flatpak': 'com.getpostman.Postman'},
                 {'id': 'intellij',
                  'name': 'IntelliJ IDEA Community',
                  'description': 'Java IDE by JetBrains.',
                  'icon': 'code',
                  'packages': {'apt': 'intellij-idea-community',
                               'pacman': 'intellij-idea-community-edition',
                               'dnf': 'intellij-idea-community',
                               'zypper': 'intellij-idea-community'},
                  'flatpak': 'com.jetbrains.IntelliJ-IDEA-Community'},
                 {'id': 'pycharm',
                  'name': 'PyCharm Community',
                  'description': 'Python IDE by JetBrains.',
                  'icon': 'code',
                  'packages': {'apt': 'pycharm-community',
                               'pacman': 'pycharm-community-edition',
                               'dnf': 'pycharm-community',
                               'zypper': 'pycharm-community'},
                  'flatpak': 'com.jetbrains.PyCharm-Community'},
                 {'id': 'android-studio',
                  'name': 'Android Studio',
                  'description': 'IDE for Android development.',
                  'icon': 'applications-development',
                  'packages': {'apt': 'android-studio',
                               'pacman': 'android-studio',
                               'dnf': 'android-studio',
                               'zypper': 'android-studio'},
                  'flatpak': 'com.google.AndroidStudio'},
                 {'id': 'dbeaver',
                  'name': 'DBeaver',
                  'description': 'Universal database tool.',
                  'icon': 'database',
                  'packages': {'apt': 'dbeaver-ce', 'pacman': 'dbeaver', 'dnf': 'dbeaver', 'zypper': 'dbeaver'},
                  'flatpak': 'io.dbeaver.DBeaverCommunity'},
                 {'id': 'insomnia',
                  'name': 'Insomnia',
                  'description': 'API client alternative to Postman.',
                  'icon': 'applications-internet',
                  'packages': {'apt': 'insomnia', 'pacman': 'insomnia', 'dnf': 'insomnia', 'zypper': 'insomnia'},
                  'flatpak': 'rest.insomnia.Insomnia'},
                 {'id': 'github-desktop',
                  'name': 'GitHub Desktop',
                  'description': 'Desktop client for GitHub workflows.',
                  'icon': 'git',
                  'packages': {'apt': '', 'pacman': '', 'dnf': '', 'zypper': ''},
                  'flatpak': 'io.github.shiftey.Desktop'},
                 {'id': 'sqlitebrowser',
                  'name': 'DB Browser for SQLite',
                  'description': 'Visual editor for SQLite databases.',
                  'icon': 'database',
                  'packages': {'apt': 'sqlitebrowser',
                               'pacman': 'sqlitebrowser',
                               'dnf': 'sqlitebrowser',
                               'zypper': 'sqlitebrowser'},
                  'flatpak': 'org.sqlitebrowser.sqlitebrowser'},
                 {'id': 'meld',
                  'name': 'Meld',
                  'description': 'Visual diff and merge tool.',
                  'icon': 'document-edit',
                  'packages': {'apt': 'meld', 'pacman': 'meld', 'dnf': 'meld', 'zypper': 'meld'},
                  'flatpak': 'org.gnome.meld'},
                 {'id': 'eclipse',
                  'name': 'Eclipse IDE',
                  'description': 'Popular IDE for Java and other languages.',
                  'icon': 'code',
                  'packages': {'apt': '', 'pacman': '', 'dnf': '', 'zypper': ''},
                  'flatpak': 'org.eclipse.Java'}],
 'Multimedia': [{'id': 'vlc',
                 'name': 'VLC',
                 'description': 'Universal media player.',
                 'icon': 'vlc',
                 'packages': {'apt': 'vlc', 'pacman': 'vlc', 'dnf': 'vlc', 'zypper': 'vlc'},
                 'flatpak': 'org.videolan.VLC'},
                {'id': 'gimp',
                 'name': 'GIMP',
                 'description': 'Image editor.',
                 'icon': 'gimp',
                 'packages': {'apt': 'gimp', 'pacman': 'gimp', 'dnf': 'gimp', 'zypper': 'gimp'},
                 'flatpak': 'org.gimp.GIMP'},
                {'id': 'pinta',
                 'name': 'Pinta',
                 'description': 'Simple drawing and image editing app for quick everyday edits.',
                 'icon': 'applications-graphics',
                 'packages': {'apt': 'pinta', 'pacman': 'pinta', 'dnf': 'pinta', 'zypper': 'pinta'},
                 'flatpak': 'com.github.PintaProject.Pinta'},
                {'id': 'obs-studio',
                 'name': 'OBS Studio',
                 'description': 'Streaming and screen recording software.',
                 'icon': 'camera-video',
                 'packages': {'apt': 'obs-studio', 'pacman': 'obs-studio', 'dnf': 'obs-studio', 'zypper': 'obs-studio'},
                 'flatpak': 'com.obsproject.Studio'},
                {'id': 'kdenlive',
                 'name': 'Kdenlive',
                 'description': 'Video editor.',
                 'icon': 'applications-multimedia',
                 'packages': {'apt': 'kdenlive', 'pacman': 'kdenlive', 'dnf': 'kdenlive', 'zypper': 'kdenlive'},
                 'flatpak': 'org.kde.kdenlive'},
                {'id': 'audacity',
                 'name': 'Audacity',
                 'description': 'Audio editor and recorder.',
                 'icon': 'audio-x-generic',
                 'packages': {'apt': 'audacity', 'pacman': 'audacity', 'dnf': 'audacity', 'zypper': 'audacity'},
                 'flatpak': 'org.audacityteam.Audacity'},
                {'id': 'spotify',
                 'name': 'Spotify',
                 'description': 'Music streaming application.',
                 'icon': 'multimedia-player',
                 'packages': {'apt': 'spotify-client',
                              'pacman': 'spotify-launcher',
                              'dnf': 'spotify-client',
                              'zypper': 'spotify-client'},
                 'flatpak': 'com.spotify.Client'},
                {'id': 'handbrake',
                 'name': 'HandBrake',
                 'description': 'Video transcoder.',
                 'icon': 'applications-multimedia',
                 'packages': {'apt': 'handbrake', 'pacman': 'handbrake', 'dnf': 'handbrake', 'zypper': 'handbrake'},
                 'flatpak': 'fr.handbrake.ghb'},
                {'id': 'krita',
                 'name': 'Krita',
                 'description': 'Digital painting software.',
                 'icon': 'applications-graphics',
                 'packages': {'apt': 'krita', 'pacman': 'krita', 'dnf': 'krita', 'zypper': 'krita'},
                 'flatpak': 'org.kde.krita'},
                {'id': 'inkscape',
                 'name': 'Inkscape',
                 'description': 'Vector graphics editor.',
                 'icon': 'applications-graphics',
                 'packages': {'apt': 'inkscape', 'pacman': 'inkscape', 'dnf': 'inkscape', 'zypper': 'inkscape'},
                 'flatpak': 'org.inkscape.Inkscape'},
                {'id': 'blender',
                 'name': 'Blender',
                 'description': '3D creation suite.',
                 'icon': 'applications-graphics',
                 'packages': {'apt': 'blender', 'pacman': 'blender', 'dnf': 'blender', 'zypper': 'blender'},
                 'flatpak': 'org.blender.Blender'},
                {'id': 'mpv',
                 'name': 'mpv',
                 'description': 'Minimalist media player with broad codec support.',
                 'icon': 'multimedia-player',
                 'packages': {'apt': 'mpv', 'pacman': 'mpv', 'dnf': 'mpv', 'zypper': 'mpv'},
                 'flatpak': 'io.mpv.Mpv'},
                {'id': 'shotcut',
                 'name': 'Shotcut',
                 'description': 'Open-source video editor.',
                 'icon': 'applications-multimedia',
                 'packages': {'apt': 'shotcut', 'pacman': 'shotcut', 'dnf': 'shotcut', 'zypper': 'shotcut'},
                 'flatpak': 'org.shotcut.Shotcut'},
                {'id': 'openshot',
                 'name': 'OpenShot',
                 'description': 'Easy-to-use open-source video editor. Native packages vary by distro, with broad '
                                'support via Flatpak.',
                 'icon': 'applications-multimedia',
                 'packages': {'apt': 'openshot-qt', 'pacman': '', 'dnf': 'openshot', 'zypper': 'openshot-qt'},
                 'flatpak': 'org.openshot.OpenShot'},
                {'id': 'losslesscut',
                 'name': 'LosslessCut',
                 'description': 'Fast tool for trimming audio and video without re-encoding.',
                 'icon': 'video-x-generic',
                 'packages': {'apt': '', 'pacman': '', 'dnf': '', 'zypper': ''},
                 'flatpak': 'no.mifi.losslesscut'}],
 'Communication': [{'id': 'telegram',
                    'name': 'Telegram Desktop',
                    'description': 'Desktop client for Telegram.',
                    'icon': 'telegram',
                    'packages': {'apt': 'telegram-desktop',
                                 'pacman': 'telegram-desktop',
                                 'dnf': 'telegram-desktop',
                                 'zypper': 'telegram-desktop'},
                    'flatpak': 'org.telegram.desktop'},
                   {'id': 'discord',
                    'name': 'Discord',
                    'description': 'Voice, chat and community platform.',
                    'icon': 'discord',
                    'packages': {'apt': 'discord', 'pacman': 'discord', 'dnf': 'discord', 'zypper': 'discord'},
                    'flatpak': 'com.discordapp.Discord'},
                   {'id': 'thunderbird',
                    'name': 'Thunderbird',
                    'description': 'Email client.',
                    'icon': 'thunderbird',
                    'packages': {'apt': 'thunderbird',
                                 'pacman': 'thunderbird',
                                 'dnf': 'thunderbird',
                                 'zypper': 'MozillaThunderbird'},
                    'flatpak': 'org.mozilla.Thunderbird'},
                   {'id': 'signal',
                    'name': 'Signal',
                    'description': 'Secure messaging application.',
                    'icon': 'mail-message-new',
                    'packages': {'apt': 'signal-desktop',
                                 'pacman': 'signal-desktop',
                                 'dnf': 'signal-desktop',
                                 'zypper': 'signal-desktop'},
                    'flatpak': 'org.signal.Signal'},
                   {'id': 'slack',
                    'name': 'Slack',
                    'description': 'Team communication platform.',
                    'icon': 'internet-chat',
                    'packages': {'apt': 'slack-desktop', 'pacman': 'slack-desktop', 'dnf': 'slack', 'zypper': 'slack'},
                    'flatpak': 'com.slack.Slack'},
                   {'id': 'zoom',
                    'name': 'Zoom',
                    'description': 'Video conferencing tool.',
                    'icon': 'camera-web',
                    'packages': {'apt': 'zoom', 'pacman': 'zoom', 'dnf': 'zoom', 'zypper': 'zoom'},
                    'flatpak': 'us.zoom.Zoom'},
                   {'id': 'element',
                    'name': 'Element',
                    'description': 'Matrix-based secure chat.',
                    'icon': 'internet-chat',
                    'packages': {'apt': 'element-desktop',
                                 'pacman': 'element-desktop',
                                 'dnf': 'element',
                                 'zypper': 'element-desktop'},
                    'flatpak': 'im.riot.Riot'}],
 'Security': [{'id': 'keepassxc',
               'name': 'KeePassXC',
               'description': 'Offline password manager.',
               'icon': 'dialog-password',
               'packages': {'apt': 'keepassxc', 'pacman': 'keepassxc', 'dnf': 'keepassxc', 'zypper': 'keepassxc'},
               'flatpak': 'org.keepassxc.KeePassXC'},
              {'id': 'bitwarden',
               'name': 'Bitwarden',
               'description': 'Cross-platform password manager.',
               'icon': 'dialog-password',
               'packages': {'apt': '', 'pacman': '', 'dnf': '', 'zypper': ''},
               'flatpak': 'com.bitwarden.desktop'},
              {'id': 'proton-pass',
               'name': 'Proton Pass',
               'description': 'Encrypted password manager and alias tool.',
               'icon': 'dialog-password',
               'packages': {'apt': '', 'pacman': '', 'dnf': '', 'zypper': ''},
               'flatpak': 'me.proton.Pass'},
              {'id': 'authenticator',
               'name': 'Authenticator',
               'description': 'Two-factor authentication code generator.',
               'icon': 'changes-prevent',
               'packages': {'apt': '', 'pacman': '', 'dnf': '', 'zypper': ''},
               'flatpak': 'com.belmoussaoui.Authenticator'},
              {'id': 'yubico-authenticator',
               'name': 'Yubico Authenticator',
               'description': 'Generate OTP codes with a YubiKey.',
               'icon': 'changes-prevent',
               'packages': {'apt': '', 'pacman': '', 'dnf': '', 'zypper': ''},
               'flatpak': 'com.yubico.yubioath'},
              {'id': 'onionshare',
               'name': 'OnionShare',
               'description': 'Securely and anonymously share files using Tor.',
               'icon': 'folder-remote',
               'packages': {'apt': '', 'pacman': '', 'dnf': '', 'zypper': ''},
               'flatpak': 'org.onionshare.OnionShare'},
              {'id': 'protonvpn',
               'name': 'Proton VPN',
               'description': 'VPN client focused on privacy and secure connections.',
               'icon': 'network-vpn',
               'packages': {'apt': '', 'pacman': '', 'dnf': '', 'zypper': ''},
               'flatpak': 'com.protonvpn.www'},
              {'id': 'mullvad-vpn',
               'name': 'Mullvad VPN',
               'description': 'Privacy-focused VPN client.',
               'icon': 'network-vpn',
               'packages': {'apt': 'mullvad-vpn', 'pacman': '', 'dnf': 'mullvad-vpn', 'zypper': ''}},
              {'id': 'wireshark',
               'name': 'Wireshark',
               'description': 'Network protocol analyzer.',
               'icon': 'network-workgroup',
               'packages': {'apt': 'wireshark', 'pacman': 'wireshark-qt', 'dnf': 'wireshark', 'zypper': 'wireshark-qt'},
               'flatpak': 'org.wireshark.Wireshark'}],
 'Utilities': [{'id': 'flatseal',
                'name': 'Flatseal',
                'description': 'Manage Flatpak permissions.',
                'icon': 'preferences-system',
                'packages': {'apt': '', 'pacman': '', 'dnf': '', 'zypper': ''},
                'flatpak': 'com.github.tchx84.Flatseal'},
               {'id': 'warehouse',
                'name': 'Warehouse',
                'description': 'Graphical manager for Flatpak applications.',
                'icon': 'system-software-install',
                'packages': {'apt': '', 'pacman': '', 'dnf': '', 'zypper': ''},
                'flatpak': 'io.github.flattool.Warehouse'},
               {'id': 'bleachbit',
                'name': 'BleachBit',
                'description': 'Privacy and cleanup utility.',
                'icon': 'edit-clear',
                'packages': {'apt': 'bleachbit', 'pacman': 'bleachbit', 'dnf': 'bleachbit', 'zypper': 'bleachbit'},
                'flatpak': 'org.bleachbit.BleachBit'},
               {'id': 'simplescreenrecorder',
                'name': 'Simple screen recorder',
                'description': 'Feature-rich screen recorder.',
                'icon': 'display',
                'packages': {'apt': 'simplescreenrecorder',
                             'pacman': 'simplescreenrecorder',
                             'dnf': 'simplescreenrecorder',
                             'zypper': 'simplescreenrecorder'}},
               {'id': 'flameshot',
                'name': 'Flameshot',
                'description': 'Screenshot and annotation tool.',
                'icon': 'camera-photo',
                'packages': {'apt': 'flameshot', 'pacman': 'flameshot', 'dnf': 'flameshot', 'zypper': 'flameshot'},
                'flatpak': 'org.flameshot.Flameshot'}],
 'Virtualization': [{'id': 'gnome-boxes',
                     'name': 'GNOME Boxes',
                     'description': 'Simple virtual machine manager.',
                     'icon': 'computer',
                     'packages': {'apt': 'gnome-boxes',
                                  'pacman': 'gnome-boxes',
                                  'dnf': 'gnome-boxes',
                                  'zypper': 'gnome-boxes'},
                     'flatpak': 'org.gnome.Boxes'},
                    {'id': 'virt-manager',
                     'name': 'Virtual Machine Manager',
                     'description': 'Advanced libvirt manager.',
                     'icon': 'computer',
                     'packages': {'apt': 'virt-manager',
                                  'pacman': 'virt-manager',
                                  'dnf': 'virt-manager',
                                  'zypper': 'virt-manager'},
                     'flatpak': 'org.virt_manager.virt-manager'},
                    {'id': 'virtualbox',
                     'name': 'Oracle VM VirtualBox',
                     'description': 'Desktop virtualization solution.',
                     'icon': 'computer',
                     'packages': {'apt': 'virtualbox',
                                  'pacman': 'virtualbox',
                                  'dnf': 'virtualbox',
                                  'zypper': 'virtualbox'}},
                    {'id': 'podman-desktop',
                     'name': 'Podman Desktop',
                     'description': 'Graphical container and Kubernetes manager.',
                     'icon': 'utilities-terminal',
                     'packages': {'apt': '', 'pacman': '', 'dnf': '', 'zypper': ''},
                     'flatpak': 'io.podman_desktop.PodmanDesktop'},
                    {'id': 'distroshelf',
                     'name': 'DistroShelf',
                     'description': 'Graphical interface for managing Distrobox containers.',
                     'icon': 'utilities-terminal',
                     'packages': {'apt': '', 'pacman': '', 'dnf': '', 'zypper': ''},
                     'flatpak': 'com.ranfdev.DistroShelf'}],
 'Office': [{'id': 'libreoffice',
             'name': 'LibreOffice',
             'description': 'Office suite.',
             'icon': 'x-office-document',
             'packages': {'apt': 'libreoffice',
                          'pacman': 'libreoffice-fresh',
                          'dnf': 'libreoffice',
                          'zypper': 'libreoffice'},
             'flatpak': 'org.libreoffice.LibreOffice'},
            {'id': 'onlyoffice',
             'name': 'ONLYOFFICE',
             'description': 'Office suite alternative.',
             'icon': 'x-office-document',
             'packages': {'apt': 'onlyoffice-desktopeditors',
                          'pacman': 'onlyoffice-bin',
                          'dnf': 'onlyoffice-desktopeditors',
                          'zypper': 'onlyoffice'},
             'flatpak': 'org.onlyoffice.desktopeditors'},
            {'id': 'calibre',
             'name': 'calibre',
             'description': 'E-book manager and reader.',
             'icon': 'x-office-document',
             'packages': {'apt': 'calibre', 'pacman': 'calibre', 'dnf': 'calibre', 'zypper': 'calibre'},
             'flatpak': 'com.calibre_ebook.calibre'},
            {'id': 'foliate',
             'name': 'Foliate',
             'description': 'Modern EPUB reader.',
             'icon': 'x-office-document',
             'packages': {'apt': 'foliate', 'pacman': 'foliate', 'dnf': 'foliate', 'zypper': 'foliate'},
             'flatpak': 'com.github.johnfactotum.Foliate'},
            {'id': 'okular',
             'name': 'Okular',
             'description': 'Document viewer for PDF, EPUB and many other formats.',
             'icon': 'application-pdf',
             'packages': {'apt': 'okular', 'pacman': 'okular', 'dnf': 'okular', 'zypper': 'okular'},
             'flatpak': 'org.kde.okular'}],
 'Productivity': [{'id': 'joplin',
                   'name': 'Joplin',
                   'description': 'Markdown notes and to-do manager.',
                   'icon': 'accessories-text-editor',
                   'packages': {'apt': '', 'pacman': '', 'dnf': '', 'zypper': ''},
                   'flatpak': 'net.cozic.joplin_desktop'},
                  {'id': 'obsidian',
                   'name': 'Obsidian',
                   'description': 'Knowledge base and Markdown note-taking app.',
                   'icon': 'accessories-text-editor',
                   'packages': {'apt': '', 'pacman': 'obsidian', 'dnf': '', 'zypper': ''},
                   'flatpak': 'md.obsidian.Obsidian'},
                  {'id': 'notion',
                   'name': 'Notion (Cohesion)',
                   'description': 'Unofficial Linux desktop client for Notion.',
                   'icon': 'accessories-text-editor',
                   'packages': {'apt': '', 'pacman': '', 'dnf': '', 'zypper': ''},
                   'flatpak': 'io.github.brunofin.Cohesion'},
                  {'id': 'appflowy',
                   'name': 'AppFlowy',
                   'description': 'Open-source workspace for notes, tasks and databases.',
                   'icon': 'accessories-text-editor',
                   'packages': {'apt': '', 'pacman': '', 'dnf': '', 'zypper': ''},
                   'flatpak': 'io.appflowy.AppFlowy'},
                  {'id': 'anytype',
                   'name': 'Anytype',
                   'description': 'Local-first workspace and knowledge base.',
                   'icon': 'accessories-text-editor',
                   'packages': {'apt': '', 'pacman': '', 'dnf': '', 'zypper': ''},
                   'flatpak': 'io.anytype.anytype'},
                  {'id': 'standard-notes',
                   'name': 'Standard Notes',
                   'description': 'Private notes application with sync support.',
                   'icon': 'accessories-text-editor',
                   'packages': {'apt': '', 'pacman': '', 'dnf': '', 'zypper': ''},
                   'flatpak': 'org.standardnotes.standardnotes'},
                  {'id': 'logseq',
                   'name': 'Logseq',
                   'description': 'Local-first knowledge base and outlining tool.',
                   'icon': 'accessories-text-editor',
                   'packages': {'apt': '', 'pacman': '', 'dnf': '', 'zypper': ''},
                   'flatpak': 'com.logseq.Logseq'},
                  {'id': 'super-productivity',
                   'name': 'Super Productivity',
                   'description': 'Task manager with time tracking.',
                   'icon': 'view-calendar-tasks',
                   'packages': {'apt': '', 'pacman': '', 'dnf': '', 'zypper': ''},
                   'flatpak': 'com.super_productivity.SuperProductivity'},
                  {'id': 'todoist',
                   'name': 'Todoist',
                   'description': 'Task and project manager.',
                   'icon': 'view-calendar-tasks',
                   'packages': {'apt': '', 'pacman': '', 'dnf': '', 'zypper': ''},
                   'flatpak': 'com.todoist.Todoist'},
                  {'id': 'ticktick',
                   'name': 'TickTick',
                   'description': 'Task manager with reminders.',
                   'icon': 'view-calendar-tasks',
                   'packages': {'apt': '', 'pacman': '', 'dnf': '', 'zypper': ''},
                   'flatpak': 'com.ticktick.TickTick'},
                  {'id': 'zotero',
                   'name': 'Zotero',
                   'description': 'Reference manager for research materials.',
                   'icon': 'x-office-document',
                   'packages': {'apt': '', 'pacman': '', 'dnf': '', 'zypper': ''},
                   'flatpak': 'org.zotero.Zotero'},
                  {'id': 'xournalpp',
                   'name': 'Xournal++',
                   'description': 'Handwritten notes and PDF annotation tool.',
                   'icon': 'draw-freehand',
                   'packages': {'apt': 'xournalpp', 'pacman': 'xournalpp', 'dnf': 'xournalpp', 'zypper': 'xournalpp'},
                   'flatpak': 'com.github.xournalpp.xournalpp'},
                  {'id': 'drawio',
                   'name': 'draw.io Desktop',
                   'description': 'Diagramming app.',
                   'icon': 'x-office-drawing',
                   'packages': {'apt': '', 'pacman': '', 'dnf': '', 'zypper': ''},
                   'flatpak': 'com.jgraph.drawio.desktop'},
                  {'id': 'anki',
                   'name': 'Anki',
                   'description': 'Spaced-repetition flashcard application.',
                   'icon': 'accessories-dictionary',
                   'packages': {'apt': '', 'pacman': '', 'dnf': '', 'zypper': ''},
                   'flatpak': 'net.ankiweb.Anki'}],
 'Gaming': [{'id': 'steam',
             'name': 'Steam',
             'description': 'Gaming platform by Valve.',
             'icon': 'steam',
             'packages': {'apt': 'steam', 'pacman': 'steam', 'dnf': 'steam', 'zypper': 'steam'},
             'flatpak': 'com.valvesoftware.Steam'},
            {'id': 'lutris',
             'name': 'Lutris',
             'description': 'Game manager for Linux.',
             'icon': 'applications-games',
             'packages': {'apt': 'lutris', 'pacman': 'lutris', 'dnf': 'lutris', 'zypper': 'lutris'},
             'flatpak': 'net.lutris.Lutris'},
            {'id': 'heroic',
             'name': 'Heroic Games Launcher',
             'description': 'Launcher for Epic, GOG and Amazon Games.',
             'icon': 'applications-games',
             'packages': {'apt': '', 'pacman': '', 'dnf': '', 'zypper': ''},
             'flatpak': 'com.heroicgameslauncher.hgl'},
            {'id': 'bottles',
             'name': 'Bottles',
             'description': 'Manage Wine environments for Windows apps and games.',
             'icon': 'applications-games',
             'packages': {'apt': '', 'pacman': '', 'dnf': '', 'zypper': ''},
             'flatpak': 'com.usebottles.bottles'},
            {'id': 'prism-launcher',
             'name': 'Prism Launcher',
             'description': 'Minecraft launcher with multi-instance support.',
             'icon': 'applications-games',
             'packages': {'apt': '', 'pacman': '', 'dnf': '', 'zypper': ''},
             'flatpak': 'org.prismlauncher.PrismLauncher'}],
 'Education': [{'id': 'geogebra',
                'name': 'GeoGebra',
                'description': 'Dynamic mathematics software.',
                'icon': 'accessories-calculator',
                'packages': {'apt': '', 'pacman': '', 'dnf': '', 'zypper': ''},
                'flatpak': 'org.geogebra.GeoGebra'},
               {'id': 'stellarium',
                'name': 'Stellarium',
                'description': 'Desktop planetarium.',
                'icon': 'applications-science',
                'packages': {'apt': 'stellarium', 'pacman': 'stellarium', 'dnf': 'stellarium', 'zypper': 'stellarium'},
                'flatpak': 'org.stellarium.Stellarium'},
               {'id': 'kiwix',
                'name': 'Kiwix',
                'description': 'Offline reader for Wikipedia.',
                'icon': 'text-html',
                'packages': {'apt': '', 'pacman': '', 'dnf': '', 'zypper': ''},
                'flatpak': 'org.kiwix.desktop'},
               {'id': 'freecad',
                'name': 'FreeCAD',
                'description': 'Parametric 3D CAD modeler.',
                'icon': 'applications-engineering',
                'packages': {'apt': 'freecad', 'pacman': 'freecad', 'dnf': 'freecad', 'zypper': 'FreeCAD'},
                'flatpak': 'org.freecad.FreeCAD'},
               {'id': 'octave',
                'name': 'GNU Octave',
                'description': 'Numerical computing environment.',
                'icon': 'accessories-calculator',
                'packages': {'apt': 'octave', 'pacman': 'octave', 'dnf': 'octave', 'zypper': 'octave'},
                'flatpak': 'org.octave.Octave'},
               {'id': 'marble',
                'name': 'Marble',
                'description': 'Virtual globe and world atlas.',
                'icon': 'globe',
                'packages': {'apt': 'marble', 'pacman': 'marble', 'dnf': 'marble', 'zypper': 'marble'},
                'flatpak': 'org.kde.marble'},
               {'id': 'gcompris',
                'name': 'GCompris',
                'description': 'Educational suite for children.',
                'icon': 'applications-education',
                'packages': {'apt': 'gcompris-qt',
                             'pacman': 'gcompris-qt',
                             'dnf': 'gcompris-qt',
                             'zypper': 'gcompris-qt'},
                'flatpak': 'org.kde.gcompris'}],
 'Networking': [{'id': 'remmina',
                 'name': 'Remmina',
                 'description': 'Remote desktop client.',
                 'icon': 'preferences-desktop-remote-desktop',
                 'packages': {'apt': 'remmina', 'pacman': 'remmina', 'dnf': 'remmina', 'zypper': 'remmina'},
                 'flatpak': 'org.remmina.Remmina'},
                {'id': 'rustdesk',
                 'name': 'RustDesk',
                 'description': 'Open-source remote desktop application.',
                 'icon': 'preferences-desktop-remote-desktop',
                 'packages': {'apt': '', 'pacman': '', 'dnf': '', 'zypper': ''},
                 'flatpak': 'com.rustdesk.RustDesk'},
                {'id': 'transmission',
                 'name': 'Transmission',
                 'description': 'Lightweight BitTorrent client.',
                 'icon': 'folder-download',
                 'packages': {'apt': 'transmission-gtk',
                              'pacman': 'transmission-gtk',
                              'dnf': 'transmission-gtk',
                              'zypper': 'transmission-gtk'},
                 'flatpak': 'com.transmissionbt.Transmission'},
                {'id': 'qbittorrent',
                 'name': 'qBittorrent',
                 'description': 'BitTorrent client.',
                 'icon': 'folder-download',
                 'packages': {'apt': 'qbittorrent',
                              'pacman': 'qbittorrent',
                              'dnf': 'qbittorrent',
                              'zypper': 'qbittorrent'},
                 'flatpak': 'org.qbittorrent.qBittorrent'},
                {'id': 'deluge',
                 'name': 'Deluge',
                 'description': 'BitTorrent client.',
                 'icon': 'folder-download',
                 'packages': {'apt': 'deluge', 'pacman': 'deluge', 'dnf': 'deluge', 'zypper': 'deluge'},
                 'flatpak': 'org.deluge_torrent.deluge'},
                {'id': 'nicotine',
                 'name': 'Nicotine+',
                 'description': 'Graphical client for the Soulseek network.',
                 'icon': 'folder-remote',
                 'packages': {'apt': '', 'pacman': '', 'dnf': '', 'zypper': ''},
                 'flatpak': 'org.nicotine_plus.Nicotine'},
                {'id': 'localsend',
                 'name': 'LocalSend',
                 'description': 'Cross-platform local network file sharing.',
                 'icon': 'network-workgroup',
                 'packages': {'apt': '', 'pacman': '', 'dnf': '', 'zypper': ''},
                 'flatpak': 'org.localsend.localsend_app'},
                {'id': 'nextcloud',
                 'name': 'Nextcloud Desktop Client',
                 'description': 'File sync and collaboration client.',
                 'icon': 'folder-cloud',
                 'packages': {'apt': 'nextcloud-desktop',
                              'pacman': 'nextcloud-client',
                              'dnf': 'nextcloud-client',
                              'zypper': 'nextcloud-desktop'},
                 'flatpak': 'com.nextcloud.desktopclient.nextcloud'},
                {'id': 'warp',
                 'name': 'Warp',
                 'description': 'Simple secure file transfer.',
                 'icon': 'folder-upload',
                 'packages': {'apt': '', 'pacman': '', 'dnf': '', 'zypper': ''},
                 'flatpak': 'app.drey.Warp'},
                {'id': 'filezilla',
                 'name': 'FileZilla',
                 'description': 'FTP/SFTP client.',
                 'icon': 'folder-remote',
                 'packages': {'apt': 'filezilla', 'pacman': 'filezilla', 'dnf': 'filezilla', 'zypper': 'filezilla'},
                 'flatpak': 'org.filezillaproject.Filezilla'}],
 'System Tools': [{'id': 'htop',
                   'name': 'htop',
                   'description': 'Interactive process viewer.',
                   'icon': 'utilities-system-monitor',
                   'packages': {'apt': 'htop', 'pacman': 'htop', 'dnf': 'htop', 'zypper': 'htop'}},
                  {'id': 'btop',
                   'name': 'btop',
                   'description': 'Terminal-based resource monitor.',
                   'icon': 'utilities-terminal',
                   'packages': {'apt': 'btop', 'pacman': 'btop', 'dnf': 'btop', 'zypper': 'btop'}},
                  {'id': 'neofetch',
                   'name': 'Neofetch',
                   'description': 'System information tool.',
                   'icon': 'utilities-terminal',
                   'packages': {'apt': 'neofetch', 'pacman': 'neofetch', 'dnf': 'neofetch', 'zypper': 'neofetch'}},
                  {'id': 'stacer',
                   'name': 'Stacer',
                   'description': 'System optimizer and monitor.',
                   'icon': 'utilities-system-monitor',
                   'packages': {'apt': 'stacer', 'pacman': 'stacer', 'dnf': 'stacer', 'zypper': 'stacer'},
                   'flatpak': 'com.github.oguzhaninan.Stacer'},
                  {'id': 'mission-center',
                   'name': 'Mission Center',
                   'description': 'Modern system monitor.',
                   'icon': 'utilities-system-monitor',
                   'packages': {'apt': '', 'pacman': '', 'dnf': '', 'zypper': ''},
                   'flatpak': 'io.missioncenter.MissionCenter'},
                  {'id': 'resources',
                   'name': 'Resources',
                   'description': 'Simple GNOME system monitor.',
                   'icon': 'utilities-system-monitor',
                   'packages': {'apt': '', 'pacman': '', 'dnf': '', 'zypper': ''},
                   'flatpak': 'net.nokyan.Resources'},
                  {'id': 'gnome-disk-utility',
                   'name': 'Disks',
                   'description': 'Disk management tool.',
                   'icon': 'drive-harddisk',
                   'packages': {'apt': 'gnome-disk-utility',
                                'pacman': 'gnome-disk-utility',
                                'dnf': 'gnome-disk-utility',
                                'zypper': 'gnome-disk-utility'}},
                  {'id': 'gparted',
                   'name': 'GParted',
                   'description': 'Partition editor.',
                   'icon': 'drive-harddisk',
                   'packages': {'apt': 'gparted', 'pacman': 'gparted', 'dnf': 'gparted', 'zypper': 'gparted'}},
                  {'id': 'baobab',
                   'name': 'Disk Usage Analyzer',
                   'description': 'Analyze disk usage.',
                   'icon': 'drive-harddisk',
                   'packages': {'apt': 'baobab', 'pacman': 'baobab', 'dnf': 'baobab', 'zypper': 'baobab'},
                   'flatpak': 'org.gnome.baobab'},
                  {'id': 'timeshift',
                   'name': 'Timeshift',
                   'description': 'System snapshot utility.',
                   'icon': 'document-save',
                   'packages': {'apt': 'timeshift', 'pacman': 'timeshift', 'dnf': 'timeshift', 'zypper': 'timeshift'}},
                  {'id': 'pika-backup',
                   'name': 'Pika Backup',
                   'description': 'Simple backup application.',
                   'icon': 'document-save',
                   'packages': {'apt': '', 'pacman': '', 'dnf': '', 'zypper': ''},
                   'flatpak': 'org.gnome.World.PikaBackup'},
                  {'id': 'cpu-x',
                   'name': 'CPU-X',
                   'description': 'Hardware information utility.',
                   'icon': 'computer',
                   'packages': {'apt': '', 'pacman': '', 'dnf': '', 'zypper': ''},
                   'flatpak': 'io.github.thetumultuousunicornofdarkness.cpu-x'},
                  {'id': 'gnome-logs',
                   'name': 'Logs',
                   'description': 'View systemd journal.',
                   'icon': 'text-x-log',
                   'packages': {'apt': 'gnome-logs',
                                'pacman': 'gnome-logs',
                                'dnf': 'gnome-logs',
                                'zypper': 'gnome-logs'},
                   'flatpak': 'org.gnome.Logs'}]}

# ==================== LOGICA COMPLETĂ ====================

_PACKAGE_BACKEND = PackageBackend()


@lru_cache(maxsize=2048)
def is_installed(pkg_name: str, manager: str | None = None) -> bool:
    manager = manager or _PACKAGE_BACKEND.pm
    if not pkg_name:
        return False
    try:
        if manager == "apt":
            return subprocess.run(["dpkg", "-s", pkg_name], stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL).returncode == 0
        if manager == "pacman":
            return subprocess.run(["pacman", "-Q", pkg_name], stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL).returncode == 0
        if manager in ("dnf", "zypper"):
            return subprocess.run(["rpm", "-q", pkg_name], stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL).returncode == 0
    except Exception:
        return False
    return False


@lru_cache(maxsize=2048)
def is_flatpak_installed(app_id: str) -> bool:
    if not app_id or shutil.which("flatpak") is None:
        return False
    try:
        return subprocess.run(["flatpak", "info", app_id], stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL).returncode == 0
    except Exception:
        return False


def app_state(app: dict) -> str:
    manager = _PACKAGE_BACKEND.pm
    native_package = (app.get("packages", {}).get(manager) or "").strip()
    flatpak_id = (app.get("flatpak") or "").strip()

    if native_package and is_installed(native_package, manager):
        return "installed-native"
    if flatpak_id and is_flatpak_installed(flatpak_id):
        return "installed-flatpak"
    if native_package:
        return "available-native"
    if flatpak_id:
        return "available-flatpak"
    return "unavailable"


def apps_for_display(search: str = "") -> Dict[str, List[dict]]:
    """Funcția principală cerută de InstallerTab"""
    query = search.lower().strip()
    result: Dict[str, List[dict]] = {}

    for category, apps in APPS.items():
        visible = []

        for app in apps:
            enriched = deepcopy(app)
            native_package = (app.get("packages", {}).get(_PACKAGE_BACKEND.pm) or "").strip()
            flatpak_id = (app.get("flatpak") or "").strip()

            state = app_state(app)

            enriched["native_package"] = native_package
            enriched["native_available"] = bool(native_package)
            enriched["flatpak_available"] = bool(flatpak_id)
            enriched["state"] = state
            enriched["source"] = "native" if native_package else "flatpak"

            # Construim dict-ul "ui" exact cum așteaptă InstallerCard
            ui = {
                "can_install": state in ("available-native", "available-flatpak"),
                "can_remove": state in ("installed-native", "installed-flatpak"),
                "can_update": False,   # poți îmbunătăți mai târziu
                "color_name": "white",
                "badge": "",
                "status_key": "installer_available",
            }

            if state == "installed-native":
                ui.update({
                    "can_remove": True,
                    "color_name": "white",
                    "status_key": "installer_installed_native",
                })
            elif state == "installed-flatpak":
                ui.update({
                    "can_remove": True,
                    "color_name": "white",
                    "status_key": "installer_installed_flatpak",
                })
            elif state == "available-native":
                ui.update({
                    "can_install": True,
                    "color_name": "green",
                    "status_key": "installer_available",
                })
            elif state == "available-flatpak":
                ui.update({
                    "can_install": True,
                    "color_name": "orange",
                    "status_key": "installer_available_flatpak",
                })
            else:
                ui.update({
                    "color_name": "red",
                    "status_key": "installer_unavailable",
                })

            enriched["ui"] = ui

            # Filtrare după căutare
            if query:
                text = f"{app.get('name','')} {app.get('description','')} {category}".lower()
                if query not in text:
                    continue

            visible.append(enriched)

        if visible:
            result[category] = visible

    return result